# -*- coding: utf-8 -*-
from PyQt5 import QtCore, QtGui, QtWidgets
from authorization_window import AuthDialog
from remont_telefonov import  Ui_Ui_Remont_Telefonov_Dialog
from remont_laptop import Ui_Ui_Remont_Laptop_Dialog


class Ui_main_window_Dialog(object):
    def setupUi(self, main_window_Dialog):
        main_window_Dialog.setObjectName("main_window_Dialog")
        main_window_Dialog.resize(1062, 902)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Pictures/Screenshot from 2025-09-15 14-30-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        main_window_Dialog.setWindowIcon(icon)
        main_window_Dialog.setStyleSheet("background-color: rgb(23, 23, 23);")
        self.gridLayout_2 = QtWidgets.QGridLayout(main_window_Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter_3 = QtWidgets.QSplitter(main_window_Dialog)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.Adres = QtWidgets.QLabel(self.splitter_3)
        self.Adres.setMaximumSize(QtCore.QSize(16777215, 20))
        self.Adres.setStyleSheet("color: rgb(154, 153, 150);\n"
"")
        self.Adres.setObjectName("Adres")
        self.Work = QtWidgets.QLabel(self.splitter_3)
        self.Work.setMaximumSize(QtCore.QSize(16777215, 20))
        self.Work.setStyleSheet("color: rgb(154, 153, 150);")
        self.Work.setObjectName("Work")
        self.gridLayout_2.addWidget(self.splitter_3, 0, 0, 1, 1)
        self.splitter_2 = QtWidgets.QSplitter(main_window_Dialog)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Logo_PushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.Logo_PushButton.setMaximumSize(QtCore.QSize(200, 70))
        self.Logo_PushButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(103, 155, 118);\n"
"")
        self.Logo_PushButton.setObjectName("Logo_PushButton")
        self.horizontalLayout_3.addWidget(self.Logo_PushButton)
        self.Search = QtWidgets.QTextEdit(self.layoutWidget)
        self.Search.setMaximumSize(QtCore.QSize(16777215, 35))
        self.Search.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.Search.setObjectName("Search")
        self.horizontalLayout_3.addWidget(self.Search)
        self.horizontalLayout.addLayout(self.horizontalLayout_3)
        self.Shop_PushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.Shop_PushButton.setStyleSheet("color: rgb(119, 118, 123);\n"
"\n"
"")
        self.Shop_PushButton.setObjectName("Shop_PushButton")
        self.horizontalLayout.addWidget(self.Shop_PushButton)
        self.Favourites_PushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.Favourites_PushButton.setStyleSheet("color: rgb(119, 118, 123);\n"
"\n"
"")
        self.Favourites_PushButton.setObjectName("Favourites_PushButton")
        self.horizontalLayout.addWidget(self.Favourites_PushButton)
        self.Basket_PushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.Basket_PushButton.setStyleSheet("color: rgb(119, 118, 123);\n"
"\n"
"")
        self.Basket_PushButton.setObjectName("Basket_PushButton")
        self.horizontalLayout.addWidget(self.Basket_PushButton)
        self.Enter_PushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.Enter_PushButton.setStyleSheet("color: rgb(119, 118, 123);\n"
"\n"
"")
        self.Enter_PushButton.setObjectName("Enter_PushButton")
        self.horizontalLayout.addWidget(self.Enter_PushButton)
        self.gridLayout_2.addWidget(self.splitter_2, 1, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(main_window_Dialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1028, 1018))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.QGL_Our_services = QtWidgets.QGridLayout()
        self.QGL_Our_services.setObjectName("QGL_Our_services")
        self.QVL_Repair_Video_Technics = QtWidgets.QVBoxLayout()
        self.QVL_Repair_Video_Technics.setObjectName("QVL_Repair_Video_Technics")
        self.QGL_Repair_Video_Technics_PB = QtWidgets.QGridLayout()
        self.QGL_Repair_Video_Technics_PB.setObjectName("QGL_Repair_Video_Technics_PB")
        self.Security_Camera_pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.Security_Camera_pushButton.setMinimumSize(QtCore.QSize(75, 75))
        self.Security_Camera_pushButton.setMaximumSize(QtCore.QSize(75, 75))
        self.Security_Camera_pushButton.setStyleSheet("background-color: rgb(103, 155, 118);\n"
"color: rgb(255, 255, 255);")
        self.Security_Camera_pushButton.setObjectName("Security_Camera_pushButton")
        self.QGL_Repair_Video_Technics_PB.addWidget(self.Security_Camera_pushButton, 0, 1, 1, 1)
        self.Video_Babysitter_pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.Video_Babysitter_pushButton.setMinimumSize(QtCore.QSize(75, 75))
        self.Video_Babysitter_pushButton.setMaximumSize(QtCore.QSize(75, 75))
        self.Video_Babysitter_pushButton.setStyleSheet("background-color: rgb(103, 155, 118);\n"
"color: rgb(255, 255, 255);")
        self.Video_Babysitter_pushButton.setObjectName("Video_Babysitter_pushButton")
        self.QGL_Repair_Video_Technics_PB.addWidget(self.Video_Babysitter_pushButton, 0, 2, 1, 1)
        self.DVR_pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.DVR_pushButton.setMinimumSize(QtCore.QSize(75, 75))
        self.DVR_pushButton.setMaximumSize(QtCore.QSize(75, 75))
        self.DVR_pushButton.setStyleSheet("background-color: rgb(103, 155, 118);\n"
"color: rgb(255, 255, 255);")
        self.DVR_pushButton.setObjectName("DVR_pushButton")
        self.QGL_Repair_Video_Technics_PB.addWidget(self.DVR_pushButton, 0, 5, 1, 1)
        self.QVL_Repair_Video_Technics.addLayout(self.QGL_Repair_Video_Technics_PB)
        self.LB_Repair_Video_Technics = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.LB_Repair_Video_Technics.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.LB_Repair_Video_Technics.setFont(font)
        self.LB_Repair_Video_Technics.setStyleSheet("background-color: rgb(103, 155, 118);\n"
"color: rgb(255, 255, 255);")
        self.LB_Repair_Video_Technics.setObjectName("LB_Repair_Video_Technics")
        self.QVL_Repair_Video_Technics.addWidget(self.LB_Repair_Video_Technics)
        self.QGL_Our_services.addLayout(self.QVL_Repair_Video_Technics, 3, 0, 1, 1)
        self.QVB_Audio_equipment_repair = QtWidgets.QVBoxLayout()
        self.QVB_Audio_equipment_repair.setObjectName("QVB_Audio_equipment_repair")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.Subwoofer_pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.Subwoofer_pushButton.setMaximumSize(QtCore.QSize(75, 75))
        self.Subwoofer_pushButton.setStyleSheet("background-color: rgb(103, 155, 118);\n"
"color: rgb(255, 255, 255);")
        self.Subwoofer_pushButton.setObjectName("Subwoofer_pushButton")
        self.gridLayout_5.addWidget(self.Subwoofer_pushButton, 0, 1, 1, 1)
        self.Columns_pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.Columns_pushButton.setMaximumSize(QtCore.QSize(75, 75))
        self.Columns_pushButton.setStyleSheet("background-color: rgb(103, 155, 118);\n"
"color: rgb(255, 255, 255);")
        self.Columns_pushButton.setObjectName("Columns_pushButton")
        self.gridLayout_5.addWidget(self.Columns_pushButton, 0, 2, 1, 1)
        self.Sound_amplifier_pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.Sound_amplifier_pushButton.setMaximumSize(QtCore.QSize(75, 75))
        self.Sound_amplifier_pushButton.setStyleSheet("background-color: rgb(103, 155, 118);\n"
"color: rgb(255, 255, 255);")
        self.Sound_amplifier_pushButton.setObjectName("Sound_amplifier_pushButton")
        self.gridLayout_5.addWidget(self.Sound_amplifier_pushButton, 0, 5, 1, 1)
        self.QVB_Audio_equipment_repair.addLayout(self.gridLayout_5)
        self.LB_Audio_equipment_repair = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.LB_Audio_equipment_repair.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.LB_Audio_equipment_repair.setFont(font)
        self.LB_Audio_equipment_repair.setStyleSheet("background-color: rgb(103, 155, 118);\n"
"color: rgb(255, 255, 255);")
        self.LB_Audio_equipment_repair.setObjectName("LB_Audio_equipment_repair")
        self.QVB_Audio_equipment_repair.addWidget(self.LB_Audio_equipment_repair)
        self.QGL_Our_services.addLayout(self.QVB_Audio_equipment_repair, 3, 2, 1, 2)
        self.Our_services = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.Our_services.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Liberation Serif")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Our_services.setFont(font)
        self.Our_services.setStyleSheet("color: rgb(255, 255, 255);")
        self.Our_services.setObjectName("Our_services")
        self.QGL_Our_services.addWidget(self.Our_services, 0, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.QGL_Our_services.addItem(spacerItem, 2, 0, 1, 1)
        self.QVL_Digital_Repair_Techniques = QtWidgets.QVBoxLayout()
        self.QVL_Digital_Repair_Techniques.setObjectName("QVL_Digital_Repair_Techniques")
        self.QGL_Digital_Repair_Techniques_PB = QtWidgets.QGridLayout()
        self.QGL_Digital_Repair_Techniques_PB.setObjectName("QGL_Digital_Repair_Techniques_PB")
        self.Tablet_pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.Tablet_pushButton.setMinimumSize(QtCore.QSize(75, 75))
        self.Tablet_pushButton.setMaximumSize(QtCore.QSize(75, 75))
        self.Tablet_pushButton.setStyleSheet("background-color: rgb(103, 155, 118);\n"
"color: rgb(255, 255, 255);")
        self.Tablet_pushButton.setObjectName("Tablet_pushButton")
        self.QGL_Digital_Repair_Techniques_PB.addWidget(self.Tablet_pushButton, 0, 3, 1, 1)
        self.TV_pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.TV_pushButton.setMinimumSize(QtCore.QSize(75, 75))
        self.TV_pushButton.setMaximumSize(QtCore.QSize(75, 75))
        self.TV_pushButton.setStyleSheet("background-color: rgb(103, 155, 118);\n"
"color: rgb(255, 255, 255);")
        self.TV_pushButton.setObjectName("TV_pushButton")
        self.QGL_Digital_Repair_Techniques_PB.addWidget(self.TV_pushButton, 1, 2, 1, 1)
        self.GameConsole_pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.GameConsole_pushButton.setMinimumSize(QtCore.QSize(75, 75))
        self.GameConsole_pushButton.setMaximumSize(QtCore.QSize(75, 75))
        self.GameConsole_pushButton.setStyleSheet("background-color: rgb(103, 155, 118);\n"
"color: rgb(255, 255, 255);")
        self.GameConsole_pushButton.setObjectName("GameConsole_pushButton")
        self.QGL_Digital_Repair_Techniques_PB.addWidget(self.GameConsole_pushButton, 1, 3, 1, 1)
        self.Laptop_pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.Laptop_pushButton.setMinimumSize(QtCore.QSize(75, 75))
        self.Laptop_pushButton.setMaximumSize(QtCore.QSize(75, 75))
        self.Laptop_pushButton.setStyleSheet("background-color: rgb(103, 155, 118);\n"
"color: rgb(255, 255, 255);")
        self.Laptop_pushButton.setObjectName("Laptop_pushButton")
        self.QGL_Digital_Repair_Techniques_PB.addWidget(self.Laptop_pushButton, 1, 0, 1, 1)
        self.Smartphone_pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.Smartphone_pushButton.setMinimumSize(QtCore.QSize(75, 75))
        self.Smartphone_pushButton.setMaximumSize(QtCore.QSize(75, 75))
        self.Smartphone_pushButton.setStyleSheet("background-color: rgb(103, 155, 118);\n"
"color: rgb(255, 255, 255);")
        self.Smartphone_pushButton.setObjectName("Smartphone_pushButton")
        self.QGL_Digital_Repair_Techniques_PB.addWidget(self.Smartphone_pushButton, 0, 0, 1, 1)
        self.Ebook_pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.Ebook_pushButton.setMinimumSize(QtCore.QSize(75, 75))
        self.Ebook_pushButton.setMaximumSize(QtCore.QSize(75, 75))
        self.Ebook_pushButton.setStyleSheet("background-color: rgb(103, 155, 118);\n"
"color: rgb(255, 255, 255);")
        self.Ebook_pushButton.setObjectName("Ebook_pushButton")
        self.QGL_Digital_Repair_Techniques_PB.addWidget(self.Ebook_pushButton, 0, 1, 1, 1)
        self.Projector_pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.Projector_pushButton.setMinimumSize(QtCore.QSize(75, 75))
        self.Projector_pushButton.setMaximumSize(QtCore.QSize(75, 75))
        self.Projector_pushButton.setStyleSheet("background-color: rgb(103, 155, 118);\n"
"color: rgb(255, 255, 255);")
        self.Projector_pushButton.setObjectName("Projector_pushButton")
        self.QGL_Digital_Repair_Techniques_PB.addWidget(self.Projector_pushButton, 1, 1, 1, 1)
        self.PhotoCamera_pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.PhotoCamera_pushButton.setMinimumSize(QtCore.QSize(75, 75))
        self.PhotoCamera_pushButton.setMaximumSize(QtCore.QSize(75, 75))
        self.PhotoCamera_pushButton.setStyleSheet("background-color: rgb(103, 155, 118);\n"
"color: rgb(255, 255, 255);")
        self.PhotoCamera_pushButton.setObjectName("PhotoCamera_pushButton")
        self.QGL_Digital_Repair_Techniques_PB.addWidget(self.PhotoCamera_pushButton, 0, 2, 1, 1)
        self.QVL_Digital_Repair_Techniques.addLayout(self.QGL_Digital_Repair_Techniques_PB)
        self.LB_Digital_Repair_Techniques = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.LB_Digital_Repair_Techniques.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.LB_Digital_Repair_Techniques.setFont(font)
        self.LB_Digital_Repair_Techniques.setStyleSheet("background-color: rgb(103, 155, 118);\n"
"color: rgb(255, 255, 255);")
        self.LB_Digital_Repair_Techniques.setObjectName("LB_Digital_Repair_Techniques")
        self.QVL_Digital_Repair_Techniques.addWidget(self.LB_Digital_Repair_Techniques)
        self.QGL_Our_services.addLayout(self.QVL_Digital_Repair_Techniques, 1, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.QVL_Repair_of_household_appliances = QtWidgets.QGridLayout()
        self.QVL_Repair_of_household_appliances.setObjectName("QVL_Repair_of_household_appliances")
        self.Vacuum_Cleaner_pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.Vacuum_Cleaner_pushButton.setMaximumSize(QtCore.QSize(75, 75))
        self.Vacuum_Cleaner_pushButton.setStyleSheet("background-color: rgb(103, 155, 118);\n"
"color: rgb(255, 255, 255);")
        self.Vacuum_Cleaner_pushButton.setObjectName("Vacuum_Cleaner_pushButton")
        self.QVL_Repair_of_household_appliances.addWidget(self.Vacuum_Cleaner_pushButton, 0, 1, 1, 1)
        self.Coffee_Machine_pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.Coffee_Machine_pushButton.setMaximumSize(QtCore.QSize(75, 75))
        self.Coffee_Machine_pushButton.setStyleSheet("background-color: rgb(103, 155, 118);\n"
"color: rgb(255, 255, 255);")
        self.Coffee_Machine_pushButton.setObjectName("Coffee_Machine_pushButton")
        self.QVL_Repair_of_household_appliances.addWidget(self.Coffee_Machine_pushButton, 0, 2, 1, 1)
        self.Fan_pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.Fan_pushButton.setMaximumSize(QtCore.QSize(75, 75))
        self.Fan_pushButton.setStyleSheet("background-color: rgb(103, 155, 118);\n"
"color: rgb(255, 255, 255);")
        self.Fan_pushButton.setObjectName("Fan_pushButton")
        self.QVL_Repair_of_household_appliances.addWidget(self.Fan_pushButton, 0, 5, 1, 1)
        self.verticalLayout_3.addLayout(self.QVL_Repair_of_household_appliances)
        self.LB_Repair_of_household_appliances = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.LB_Repair_of_household_appliances.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.LB_Repair_of_household_appliances.setFont(font)
        self.LB_Repair_of_household_appliances.setStyleSheet("background-color: rgb(103, 155, 118);\n"
"color: rgb(255, 255, 255);")
        self.LB_Repair_of_household_appliances.setObjectName("LB_Repair_of_household_appliances")
        self.verticalLayout_3.addWidget(self.LB_Repair_of_household_appliances)
        self.QGL_Our_services.addLayout(self.verticalLayout_3, 1, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.QGL_Our_services.addItem(spacerItem1, 3, 1, 1, 1)
        self.gridLayout.addLayout(self.QGL_Our_services, 0, 0, 1, 1)
        self.QVB_Repair_of_equipment_of_any_kind = QtWidgets.QVBoxLayout()
        self.QVB_Repair_of_equipment_of_any_kind.setObjectName("QVB_Repair_of_equipment_of_any_kind")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.QVB_Repair_of_equipment_of_any_kind.addItem(spacerItem2)
        self.LB_Repair_of_equipment_of_any_kind = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.LB_Repair_of_equipment_of_any_kind.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Liberation Serif")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.LB_Repair_of_equipment_of_any_kind.setFont(font)
        self.LB_Repair_of_equipment_of_any_kind.setStyleSheet("color: rgb(255, 255, 255);")
        self.LB_Repair_of_equipment_of_any_kind.setObjectName("LB_Repair_of_equipment_of_any_kind")
        self.QVB_Repair_of_equipment_of_any_kind.addWidget(self.LB_Repair_of_equipment_of_any_kind)
        self.TEXT_Repair_of_equipment_of_any_kind = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.TEXT_Repair_of_equipment_of_any_kind.setStyleSheet("color: rgb(255, 255, 255);")
        self.TEXT_Repair_of_equipment_of_any_kind.setObjectName("TEXT_Repair_of_equipment_of_any_kind")
        self.QVB_Repair_of_equipment_of_any_kind.addWidget(self.TEXT_Repair_of_equipment_of_any_kind)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.QVB_Repair_of_equipment_of_any_kind.addItem(spacerItem3)
        self.gridLayout.addLayout(self.QVB_Repair_of_equipment_of_any_kind, 1, 0, 1, 1)
        self.QVB_Our_Advantage = QtWidgets.QVBoxLayout()
        self.QVB_Our_Advantage.setObjectName("QVB_Our_Advantage")
        self.LB_Our_Advantage = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.LB_Our_Advantage.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Liberation Serif")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.LB_Our_Advantage.setFont(font)
        self.LB_Our_Advantage.setStyleSheet("color: rgb(255, 255, 255);")
        self.LB_Our_Advantage.setObjectName("LB_Our_Advantage")
        self.QVB_Our_Advantage.addWidget(self.LB_Our_Advantage)
        self.splitter = QtWidgets.QSplitter(self.scrollAreaWidgetContents)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.Professional_pushButton = QtWidgets.QPushButton(self.splitter)
        self.Professional_pushButton.setMinimumSize(QtCore.QSize(100, 100))
        self.Professional_pushButton.setMaximumSize(QtCore.QSize(100, 100))
        self.Professional_pushButton.setStyleSheet("background-color: rgb(119, 118, 123);\n"
"selection-background-color: rgb(103, 155, 118);\n"
"color: rgb(255, 255, 255);")
        self.Professional_pushButton.setObjectName("Professional_pushButton")
        self.Complexity_pushButton = QtWidgets.QPushButton(self.splitter)
        self.Complexity_pushButton.setMinimumSize(QtCore.QSize(100, 100))
        self.Complexity_pushButton.setMaximumSize(QtCore.QSize(100, 100))
        self.Complexity_pushButton.setStyleSheet("background-color: rgb(119, 118, 123);\n"
"selection-background-color: rgb(103, 155, 118);\n"
"color: rgb(255, 255, 255);")
        self.Complexity_pushButton.setObjectName("Complexity_pushButton")
        self.Equipment_pushButton = QtWidgets.QPushButton(self.splitter)
        self.Equipment_pushButton.setMinimumSize(QtCore.QSize(100, 100))
        self.Equipment_pushButton.setMaximumSize(QtCore.QSize(100, 100))
        self.Equipment_pushButton.setStyleSheet("background-color: rgb(119, 118, 123);\n"
"selection-background-color: rgb(103, 155, 118);\n"
"color: rgb(255, 255, 255);")
        self.Equipment_pushButton.setObjectName("Equipment_pushButton")
        self.Quickly_pushButton = QtWidgets.QPushButton(self.splitter)
        self.Quickly_pushButton.setMinimumSize(QtCore.QSize(100, 100))
        self.Quickly_pushButton.setMaximumSize(QtCore.QSize(100, 100))
        self.Quickly_pushButton.setStyleSheet("background-color: rgb(119, 118, 123);\n"
"selection-background-color: rgb(103, 155, 118);\n"
"color: rgb(255, 255, 255);")
        self.Quickly_pushButton.setObjectName("Quickly_pushButton")
        self.Available_pushButton = QtWidgets.QPushButton(self.splitter)
        self.Available_pushButton.setMinimumSize(QtCore.QSize(100, 100))
        self.Available_pushButton.setMaximumSize(QtCore.QSize(100, 100))
        self.Available_pushButton.setStyleSheet("background-color: rgb(119, 118, 123);\n"
"selection-background-color: rgb(103, 155, 118);\n"
"color: rgb(255, 255, 255);")
        self.Available_pushButton.setObjectName("Available_pushButton")
        self.pushButton_34 = QtWidgets.QPushButton(self.splitter)
        self.pushButton_34.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_34.setMaximumSize(QtCore.QSize(100, 100))
        self.pushButton_34.setStyleSheet("background-color: rgb(119, 118, 123);\n"
"selection-background-color: rgb(103, 155, 118);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_34.setObjectName("pushButton_34")
        self.QVB_Our_Advantage.addWidget(self.splitter)
        self.TXT_Our_Advantage = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.TXT_Our_Advantage.setMinimumSize(QtCore.QSize(100, 200))
        self.TXT_Our_Advantage.setStyleSheet("color: rgb(255, 255, 255);")
        self.TXT_Our_Advantage.setObjectName("TXT_Our_Advantage")
        self.QVB_Our_Advantage.addWidget(self.TXT_Our_Advantage)
        self.gridLayout.addLayout(self.QVB_Our_Advantage, 2, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 3, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Service_pushButton = QtWidgets.QPushButton(main_window_Dialog)
        self.Service_pushButton.setStyleSheet("color: rgb(255, 255, 255);")
        self.Service_pushButton.setObjectName("Service_pushButton")
        self.horizontalLayout_4.addWidget(self.Service_pushButton)
        self.About_pushButton = QtWidgets.QPushButton(main_window_Dialog)
        self.About_pushButton.setStyleSheet("color: rgb(255, 255, 255);")
        self.About_pushButton.setObjectName("About_pushButton")
        self.horizontalLayout_4.addWidget(self.About_pushButton)
        self.Price_pushButton = QtWidgets.QPushButton(main_window_Dialog)
        self.Price_pushButton.setStyleSheet("color: rgb(255, 255, 255);")
        self.Price_pushButton.setObjectName("Price_pushButton")
        self.horizontalLayout_4.addWidget(self.Price_pushButton)
        self.Delivery_pushButton = QtWidgets.QPushButton(main_window_Dialog)
        self.Delivery_pushButton.setStyleSheet("color: rgb(255, 255, 255);")
        self.Delivery_pushButton.setObjectName("Delivery_pushButton")
        self.horizontalLayout_4.addWidget(self.Delivery_pushButton)
        self.Reviews_pushButton = QtWidgets.QPushButton(main_window_Dialog)
        self.Reviews_pushButton.setStyleSheet("color: rgb(255, 255, 255);")
        self.Reviews_pushButton.setObjectName("Reviews_pushButton")
        self.horizontalLayout_4.addWidget(self.Reviews_pushButton)
        self.Vacancy_pushButton = QtWidgets.QPushButton(main_window_Dialog)
        self.Vacancy_pushButton.setStyleSheet("color: rgb(255, 255, 255);")
        self.Vacancy_pushButton.setObjectName("Vacancy_pushButton")
        self.horizontalLayout_4.addWidget(self.Vacancy_pushButton)
        self.Article_pushButton = QtWidgets.QPushButton(main_window_Dialog)
        self.Article_pushButton.setStyleSheet("color: rgb(255, 255, 255);")
        self.Article_pushButton.setObjectName("Article_pushButton")
        self.horizontalLayout_4.addWidget(self.Article_pushButton)
        self.Contacts_pushButton = QtWidgets.QPushButton(main_window_Dialog)
        self.Contacts_pushButton.setStyleSheet("color: rgb(255, 255, 255);")
        self.Contacts_pushButton.setObjectName("Contacts_pushButton")
        self.horizontalLayout_4.addWidget(self.Contacts_pushButton)
        self.XYZ_pushButton = QtWidgets.QPushButton(main_window_Dialog)
        self.XYZ_pushButton.setStyleSheet("color: rgb(255, 255, 255);")
        self.XYZ_pushButton.setObjectName("XYZ_pushButton")
        self.horizontalLayout_4.addWidget(self.XYZ_pushButton)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)

        self.Enter_PushButton.clicked.connect(self.open_auth_window)
        self.Laptop_pushButton.clicked.connect(self.open_remont_laptop)
        self.Smartphone_pushButton.clicked.connect(self.open_remont_telefonov)
        self.retranslateUi(main_window_Dialog)
        QtCore.QMetaObject.connectSlotsByName(main_window_Dialog)

    def retranslateUi(self, main_window_Dialog):
        _translate = QtCore.QCoreApplication.translate
        main_window_Dialog.setWindowTitle(_translate("main_window_Dialog", "IT-EcoSystem"))
        self.Adres.setText(_translate("main_window_Dialog", "🗺️ ​Красноярск, Улица Микуцкого, 12"))
        self.Work.setText(_translate("main_window_Dialog", "📅 Пн-Пт: 10:00-20:00 | Сб-Вс: 12:00-19:00"))
        self.Logo_PushButton.setText(_translate("main_window_Dialog", "Логотип"))
        self.Search.setPlaceholderText(_translate("main_window_Dialog", "Поиск"))
        self.Shop_PushButton.setText(_translate("main_window_Dialog", "Магазины"))
        self.Favourites_PushButton.setText(_translate("main_window_Dialog", "Избраное"))
        self.Basket_PushButton.setText(_translate("main_window_Dialog", "Корзина"))
        self.Enter_PushButton.setText(_translate("main_window_Dialog", "Войти"))
        self.Security_Camera_pushButton.setText(_translate("main_window_Dialog", "Вид набл"))
        self.Video_Babysitter_pushButton.setText(_translate("main_window_Dialog", "Вид няня"))
        self.DVR_pushButton.setText(_translate("main_window_Dialog", "Вид регис"))
        self.LB_Repair_Video_Technics.setText(_translate("main_window_Dialog", "Ремонт видео технике"))
        self.Subwoofer_pushButton.setText(_translate("main_window_Dialog", "Сабвуф"))
        self.Columns_pushButton.setText(_translate("main_window_Dialog", "Колонки"))
        self.Sound_amplifier_pushButton.setText(_translate("main_window_Dialog", "Усел звук"))
        self.LB_Audio_equipment_repair.setText(_translate("main_window_Dialog", "Ремонт аудио технике"))
        self.Our_services.setText(_translate("main_window_Dialog", "Наши услуи:"))
        self.Tablet_pushButton.setText(_translate("main_window_Dialog", "Планшет"))
        self.TV_pushButton.setText(_translate("main_window_Dialog", "Телевизор"))
        self.GameConsole_pushButton.setText(_translate("main_window_Dialog", "Игр. Прист"))
        self.Laptop_pushButton.setText(_translate("main_window_Dialog", "Ноутбук"))
        self.Smartphone_pushButton.setText(_translate("main_window_Dialog", "Телефон"))
        self.Ebook_pushButton.setText(_translate("main_window_Dialog", "Эл. книги"))
        self.Projector_pushButton.setText(_translate("main_window_Dialog", "Проектор"))
        self.PhotoCamera_pushButton.setText(_translate("main_window_Dialog", "Фотоопарат"))
        self.LB_Digital_Repair_Techniques.setText(_translate("main_window_Dialog", "Ремонт цифровой технике"))
        self.Vacuum_Cleaner_pushButton.setText(_translate("main_window_Dialog", "Пылесосы"))
        self.Coffee_Machine_pushButton.setText(_translate("main_window_Dialog", "Кофемаш"))
        self.Fan_pushButton.setText(_translate("main_window_Dialog", "Тепловинт"))
        self.LB_Repair_of_household_appliances.setText(_translate("main_window_Dialog", "Ремонт бытовой технике"))
        self.LB_Repair_of_equipment_of_any_kind.setText(_translate("main_window_Dialog", "Ремонт техники любых видов:"))
        self.TEXT_Repair_of_equipment_of_any_kind.setText(_translate("main_window_Dialog", "<html><head/><body><p>Жизнь современного человека невозможно представить без электроники,</p><p>и ее выход из строя очень часто чреват не только личными неудобствами,</p><p>но и материальными потерями, ведь такое оборудование обеспечивает многие рабочие процессы. </p><p>Поэтому очень важно, чтобы ремонт электроники был не только безупречно качественным, но и оперативным. </p><p>Сервисный центр «IT-EcoSustem» гарантирует выполнение услуг на высоком профессиональном уровне и точно в оговоренные сроки. </p><p>При этом стоимость работ всегда остается максимально доступной и объективной,</p><p>ведь наш приоритет – высококачественный сервис и доверие клиентов, а не материальная выгода.</p></body></html>"))
        self.LB_Our_Advantage.setText(_translate("main_window_Dialog", "Наши преимущество: "))
        self.Professional_pushButton.setText(_translate("main_window_Dialog", "Профессиональность"))
        self.Complexity_pushButton.setText(_translate("main_window_Dialog", "Любая сложность"))
        self.Equipment_pushButton.setText(_translate("main_window_Dialog", "Оборудование"))
        self.Quickly_pushButton.setText(_translate("main_window_Dialog", "Быстро"))
        self.Available_pushButton.setText(_translate("main_window_Dialog", "Доступно"))
        self.pushButton_34.setText(_translate("main_window_Dialog", "Гарантия"))
        self.TXT_Our_Advantage.setText(_translate("main_window_Dialog", "TextLabel"))
        self.Service_pushButton.setText(_translate("main_window_Dialog", "Услуги"))
        self.About_pushButton.setText(_translate("main_window_Dialog", "О нас"))
        self.Price_pushButton.setText(_translate("main_window_Dialog", "Цена"))
        self.Delivery_pushButton.setText(_translate("main_window_Dialog", "Доставка"))
        self.Reviews_pushButton.setText(_translate("main_window_Dialog", "Отзывы"))
        self.Vacancy_pushButton.setText(_translate("main_window_Dialog", "Вакансии"))
        self.Article_pushButton.setText(_translate("main_window_Dialog", "Статьи"))
        self.Contacts_pushButton.setText(_translate("main_window_Dialog", "Контакты"))
        self.XYZ_pushButton.setText(_translate("main_window_Dialog", "PushButton"))

    def open_auth_window(self):
        self.Dialog = QtWidgets.QDialog()
        self.ui = AuthDialog()
        self.ui.setupUi(self.Dialog)
        self.Dialog.show()

    def open_remont_telefonov(self):
        self.Dialog = QtWidgets.QDialog()
        self.ui = Ui_Ui_Remont_Telefonov_Dialog()
        self.ui.setupUi(self.Dialog)
        self.Dialog.show()

    def open_remont_laptop(self):
            self.Dialog = QtWidgets.QDialog()
            self.ui = Ui_Ui_Remont_Laptop_Dialog()
            self.ui.setupUi(self.Dialog)
            self.Dialog.show()