# -*- coding: utf-8 -*-
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ui_Remont_Laptop_Dialog(object):
    def setupUi(self, Ui_Remont_Laptop_Dialog):
        Ui_Remont_Laptop_Dialog.setObjectName("Ui_Remont_Laptop_Dialog")
        Ui_Remont_Laptop_Dialog.resize(867, 960)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Pictures/Screenshot from 2025-09-15 14-30-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Ui_Remont_Laptop_Dialog.setWindowIcon(icon)
        Ui_Remont_Laptop_Dialog.setStyleSheet("background-color: rgb(47, 47, 47);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Ui_Remont_Laptop_Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(Ui_Remont_Laptop_Dialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.QW_Remont_laptop = QtWidgets.QWidget()
        self.QW_Remont_laptop.setGeometry(QtCore.QRect(0, 0, 853, 926))
        self.QW_Remont_laptop.setObjectName("QW_Remont_laptop")
        self.gridLayout = QtWidgets.QGridLayout(self.QW_Remont_laptop)
        self.gridLayout.setObjectName("gridLayout")
        self.LB1_Remont_laptop = QtWidgets.QLabel(self.QW_Remont_laptop)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LB1_Remont_laptop.setFont(font)
        self.LB1_Remont_laptop.setStyleSheet("color: rgb(255, 255, 255);")
        self.LB1_Remont_laptop.setObjectName("LB1_Remont_laptop")
        self.gridLayout.addWidget(self.LB1_Remont_laptop, 0, 0, 1, 1)
        self.TW_Remont_laptop = QtWidgets.QTableWidget(self.QW_Remont_laptop)
        self.TW_Remont_laptop.setMinimumSize(QtCore.QSize(725, 320))
        self.TW_Remont_laptop.setMaximumSize(QtCore.QSize(725, 210))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TW_Remont_laptop.setFont(font)
        self.TW_Remont_laptop.setStyleSheet("color: rgb(255, 255, 255);")
        self.TW_Remont_laptop.setRowCount(8)
        self.TW_Remont_laptop.setColumnCount(1)
        self.TW_Remont_laptop.setObjectName("TW_Remont_laptop")
        item = QtWidgets.QTableWidgetItem()
        self.TW_Remont_laptop.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TW_Remont_laptop.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TW_Remont_laptop.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TW_Remont_laptop.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TW_Remont_laptop.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.TW_Remont_laptop.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.TW_Remont_laptop.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.TW_Remont_laptop.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        item.setBackground(QtGui.QColor(103, 155, 118))
        self.TW_Remont_laptop.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.TW_Remont_laptop.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.TW_Remont_laptop.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TW_Remont_laptop.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TW_Remont_laptop.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TW_Remont_laptop.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TW_Remont_laptop.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TW_Remont_laptop.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TW_Remont_laptop.setItem(7, 0, item)
        self.TW_Remont_laptop.horizontalHeader().setDefaultSectionSize(500)
        self.gridLayout.addWidget(self.TW_Remont_laptop, 1, 0, 1, 1)
        self.LB2_Remont_laptop = QtWidgets.QLabel(self.QW_Remont_laptop)
        self.LB2_Remont_laptop.setMinimumSize(QtCore.QSize(0, 0))
        self.LB2_Remont_laptop.setMaximumSize(QtCore.QSize(725, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LB2_Remont_laptop.setFont(font)
        self.LB2_Remont_laptop.setStyleSheet("color: rgb(255, 255, 255);")
        self.LB2_Remont_laptop.setObjectName("LB2_Remont_laptop")
        self.gridLayout.addWidget(self.LB2_Remont_laptop, 2, 0, 1, 1)
        self.scrollArea.setWidget(self.QW_Remont_laptop)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(Ui_Remont_Laptop_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Ui_Remont_Laptop_Dialog)

    def retranslateUi(self, Ui_Remont_Laptop_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Ui_Remont_Laptop_Dialog.setWindowTitle(_translate("Ui_Remont_Laptop_Dialog", "IT-EcoSystem"))
        self.LB1_Remont_laptop.setText(_translate("Ui_Remont_Laptop_Dialog", "<html><head/><body><h1 style=\" margin-top:18px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:xx-large; font-weight:600;\">Ремонт ноутбуков</span></h1><p>Ноутбуки чаще другой компьютерной техники требуют ремонта, что обычно связано с экстремальными условиями их эксплуатации. </p><p>Среди владельцев ноутбуков наиболее частыми поводами для обращения в сервис являются залитая клавиатура и механические </p><p>повреждения корпуса, что не характерно при ремонте стационарных ПК. При этом процессоры в ноутбуках страдают значительно реже.</p></body></html>"))
        item = self.TW_Remont_laptop.verticalHeaderItem(0)
        item.setText(_translate("Ui_Remont_Laptop_Dialog", "Техническое обслуживание с заменой термопасты"))
        item = self.TW_Remont_laptop.verticalHeaderItem(1)
        item.setText(_translate("Ui_Remont_Laptop_Dialog", "Техническое обслуживание без замены термопасты"))
        item = self.TW_Remont_laptop.verticalHeaderItem(2)
        item.setText(_translate("Ui_Remont_Laptop_Dialog", "Замена матрицы"))
        item = self.TW_Remont_laptop.verticalHeaderItem(3)
        item.setText(_translate("Ui_Remont_Laptop_Dialog", "Ремонт платы"))
        item = self.TW_Remont_laptop.verticalHeaderItem(4)
        item.setText(_translate("Ui_Remont_Laptop_Dialog", "Восстановление разъема"))
        item = self.TW_Remont_laptop.verticalHeaderItem(5)
        item.setText(_translate("Ui_Remont_Laptop_Dialog", "Переустановка Windows"))
        item = self.TW_Remont_laptop.verticalHeaderItem(6)
        item.setText(_translate("Ui_Remont_Laptop_Dialog", "Установка программ"))
        item = self.TW_Remont_laptop.verticalHeaderItem(7)
        item.setText(_translate("Ui_Remont_Laptop_Dialog", "Ремонт кнопок"))
        item = self.TW_Remont_laptop.horizontalHeaderItem(0)
        item.setText(_translate("Ui_Remont_Laptop_Dialog", "Цена за ремонт ноутбуков"))
        __sortingEnabled = self.TW_Remont_laptop.isSortingEnabled()
        self.TW_Remont_laptop.setSortingEnabled(False)
        item = self.TW_Remont_laptop.item(0, 0)
        item.setText(_translate("Ui_Remont_Laptop_Dialog", "от 1600 руб."))
        item = self.TW_Remont_laptop.item(1, 0)
        item.setText(_translate("Ui_Remont_Laptop_Dialog", "от 1300 руб."))
        item = self.TW_Remont_laptop.item(2, 0)
        item.setText(_translate("Ui_Remont_Laptop_Dialog", "от 1000 руб."))
        item = self.TW_Remont_laptop.item(3, 0)
        item.setText(_translate("Ui_Remont_Laptop_Dialog", "от 1100 руб."))
        item = self.TW_Remont_laptop.item(4, 0)
        item.setText(_translate("Ui_Remont_Laptop_Dialog", "от 800 руб."))
        item = self.TW_Remont_laptop.item(5, 0)
        item.setText(_translate("Ui_Remont_Laptop_Dialog", "от 1000 руб."))
        item = self.TW_Remont_laptop.item(6, 0)
        item.setText(_translate("Ui_Remont_Laptop_Dialog", "от 600 руб."))
        item = self.TW_Remont_laptop.item(7, 0)
        item.setText(_translate("Ui_Remont_Laptop_Dialog", "от 800 руб."))
        self.TW_Remont_laptop.setSortingEnabled(__sortingEnabled)
        self.LB2_Remont_laptop.setText(_translate("Ui_Remont_Laptop_Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Есть несколько факторов, которые усложняют диагностику и ремонт любого ноутбука: </span></p><ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Маленький размер деталей: ноутбук только кажется простым устройством, однако именно благодаря «мелкокалиберным» комплектующим он приобретает компактность. </li><li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Уникальная компоновка элементов: свойственна каждой модели, поэтому для ремонта ноутбуков можно использовать только оригинальные комплектующие – это же обстоятельство затрудняет поиск необходимой детали. </li><li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Диагностические мероприятия: предшествуют ремонту ноутбука и обязательны как для всей системы в целом, так и для отдельных ее компонентов.</li></ul><p>У каждого производителя и даже модели ноутбука свои «слабости», что упрощает задачу мастера. Однако в этом случае очень важны опыт и квалификация сотрудников ремонтной мастерской, а также непрерывное развитие. Технологии не стоят на месте, и появляются новые модели ноутбуков со свойственными только им «болезнями». </p><p>Чтобы ваш ноутбук долго не выходил из строя, необходимо эксплуатировать его бережно. Но если ноутбук не заряжается или не включается, самопроизвольно выключается, наблюдается ухудшение изображения или отказ клавиатуры, компьютеру необходима диагностика. Любые неполадки в работе девайса – повод обратиться в мастерскую.<br/></p><p>Чтобы узнать цены на услуги по ремонту, позвоните в мастерскую по номеру +7 (***) ***-**-**.</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ui_Remont_Laptop_Dialog = QtWidgets.QDialog()
    ui = Ui_Ui_Remont_Laptop_Dialog()
    ui.setupUi(Ui_Remont_Laptop_Dialog)
    Ui_Remont_Laptop_Dialog.show()
    sys.exit(app.exec_())
