# -*- coding: utf-8 -*-
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ui_Remont_Telefonov_Dialog(object):
    def setupUi(self, Ui_Remont_Telefonov_Dialog):
        Ui_Remont_Telefonov_Dialog.setObjectName("Ui_Remont_Telefonov_Dialog")
        Ui_Remont_Telefonov_Dialog.resize(917, 960)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Pictures/Screenshot from 2025-09-15 14-30-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Ui_Remont_Telefonov_Dialog.setWindowIcon(icon)
        Ui_Remont_Telefonov_Dialog.setStyleSheet("background-color: rgb(47, 47, 47);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Ui_Remont_Telefonov_Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(Ui_Remont_Telefonov_Dialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.QW_Remont_telefonov = QtWidgets.QWidget()
        self.QW_Remont_telefonov.setGeometry(QtCore.QRect(0, 0, 889, 959))
        self.QW_Remont_telefonov.setObjectName("QW_Remont_telefonov")
        self.gridLayout = QtWidgets.QGridLayout(self.QW_Remont_telefonov)
        self.gridLayout.setObjectName("gridLayout")
        self.LB1_Remont_telefonov = QtWidgets.QLabel(self.QW_Remont_telefonov)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LB1_Remont_telefonov.setFont(font)
        self.LB1_Remont_telefonov.setStyleSheet("color: rgb(255, 255, 255);")
        self.LB1_Remont_telefonov.setObjectName("LB1_Remont_telefonov")
        self.gridLayout.addWidget(self.LB1_Remont_telefonov, 0, 0, 1, 1)
        self.TW_Remont_telefonov = QtWidgets.QTableWidget(self.QW_Remont_telefonov)
        self.TW_Remont_telefonov.setMinimumSize(QtCore.QSize(725, 210))
        self.TW_Remont_telefonov.setMaximumSize(QtCore.QSize(725, 210))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TW_Remont_telefonov.setFont(font)
        self.TW_Remont_telefonov.setStyleSheet("color: rgb(255, 255, 255);")
        self.TW_Remont_telefonov.setRowCount(6)
        self.TW_Remont_telefonov.setColumnCount(1)
        self.TW_Remont_telefonov.setObjectName("TW_Remont_telefonov")
        item = QtWidgets.QTableWidgetItem()
        self.TW_Remont_telefonov.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TW_Remont_telefonov.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TW_Remont_telefonov.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TW_Remont_telefonov.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TW_Remont_telefonov.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.TW_Remont_telefonov.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        item.setBackground(QtGui.QColor(103, 155, 118))
        self.TW_Remont_telefonov.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.TW_Remont_telefonov.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.TW_Remont_telefonov.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TW_Remont_telefonov.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TW_Remont_telefonov.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TW_Remont_telefonov.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TW_Remont_telefonov.setItem(5, 0, item)
        self.TW_Remont_telefonov.horizontalHeader().setDefaultSectionSize(500)
        self.gridLayout.addWidget(self.TW_Remont_telefonov, 1, 0, 1, 1)
        self.LB2_Remont_telefonov = QtWidgets.QLabel(self.QW_Remont_telefonov)
        self.LB2_Remont_telefonov.setMinimumSize(QtCore.QSize(0, 0))
        self.LB2_Remont_telefonov.setMaximumSize(QtCore.QSize(725, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LB2_Remont_telefonov.setFont(font)
        self.LB2_Remont_telefonov.setStyleSheet("color: rgb(255, 255, 255);")
        self.LB2_Remont_telefonov.setObjectName("LB2_Remont_telefonov")
        self.gridLayout.addWidget(self.LB2_Remont_telefonov, 2, 0, 1, 1)
        self.scrollArea.setWidget(self.QW_Remont_telefonov)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(Ui_Remont_Telefonov_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Ui_Remont_Telefonov_Dialog)

    def retranslateUi(self, Ui_Remont_Telefonov_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Ui_Remont_Telefonov_Dialog.setWindowTitle(_translate("Ui_Remont_Telefonov_Dialog", "IT-EcoSystem"))
        self.LB1_Remont_telefonov.setText(_translate("Ui_Remont_Telefonov_Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Ремонт телефонов любой сложности</span></p><p>Сервисный центр «IT-EcoSystem» занимается ремонтом мобильных телефонов. </p><p>Специалисты производят обслуживание кнопочных устройств и новейших смартфонов разных брендов:</p><p>iPhone, Samsung, Lenovo, LG, HTC, Sony, Vertu, Highscreen и др.</p><p>При необходимости осуществляется доставка гаджетов по Красноярску.</p><p><br/></p><p>На складе постоянно в наличии сертифицированные комплектующие для срочной замены износившихся узлов. </p><p>Если есть техническая возможность, сотрудники мастерской производят профессиональное устранение неполадок на компонентном уровне, </p><p>включая перепайку микросхем разной сложности.</p></body></html>"))
        item = self.TW_Remont_telefonov.verticalHeaderItem(0)
        item.setText(_translate("Ui_Remont_Telefonov_Dialog", "Восстановление/замена разъема"))
        item = self.TW_Remont_telefonov.verticalHeaderItem(1)
        item.setText(_translate("Ui_Remont_Telefonov_Dialog", "Замена тачскрина или дисплея"))
        item = self.TW_Remont_telefonov.verticalHeaderItem(2)
        item.setText(_translate("Ui_Remont_Telefonov_Dialog", "Ремонт электроники"))
        item = self.TW_Remont_telefonov.verticalHeaderItem(3)
        item.setText(_translate("Ui_Remont_Telefonov_Dialog", "Замена динамика"))
        item = self.TW_Remont_telefonov.verticalHeaderItem(4)
        item.setText(_translate("Ui_Remont_Telefonov_Dialog", "Восстановление после залития"))
        item = self.TW_Remont_telefonov.verticalHeaderItem(5)
        item.setText(_translate("Ui_Remont_Telefonov_Dialog", "Ремонт Wi-Fi и GSM модуля"))
        item = self.TW_Remont_telefonov.horizontalHeaderItem(0)
        item.setText(_translate("Ui_Remont_Telefonov_Dialog", "Цена за ремонт телефонов"))
        __sortingEnabled = self.TW_Remont_telefonov.isSortingEnabled()
        self.TW_Remont_telefonov.setSortingEnabled(False)
        item = self.TW_Remont_telefonov.item(0, 0)
        item.setText(_translate("Ui_Remont_Telefonov_Dialog", "от 800 руб."))
        item = self.TW_Remont_telefonov.item(1, 0)
        item.setText(_translate("Ui_Remont_Telefonov_Dialog", "от 1300 руб."))
        item = self.TW_Remont_telefonov.item(2, 0)
        item.setText(_translate("Ui_Remont_Telefonov_Dialog", "от 1000 руб."))
        item = self.TW_Remont_telefonov.item(3, 0)
        item.setText(_translate("Ui_Remont_Telefonov_Dialog", "от 800 руб."))
        item = self.TW_Remont_telefonov.item(4, 0)
        item.setText(_translate("Ui_Remont_Telefonov_Dialog", "от 1500 руб."))
        item = self.TW_Remont_telefonov.item(5, 0)
        item.setText(_translate("Ui_Remont_Telefonov_Dialog", "от 1200 руб."))
        self.TW_Remont_telefonov.setSortingEnabled(__sortingEnabled)
        self.LB2_Remont_telefonov.setText(_translate("Ui_Remont_Telefonov_Dialog", "<html><head/><body><h2 style=\" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:x-large; font-weight:600;\">Все виды ремонта мобильных телефонов</span></h2><p>Специалисты сервисного центра предоставляют все услуги, которые</p><p>могут понадобиться для восстановления работоспособности гаджета:</p><ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">меняют стекло или дисплей полностью, камеру, кнопку включения, корпус, </li><p>динамики, разъемы USB/micro-USB, кнопки громкости и прочие поврежденные части;</p><li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">производят качественную чистку от пыли и влаги (в сервисном центре можно заказать ремонт </li><p>сотового телефона после попадания в него воды);</p><li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">восстанавливают архитектуру и топологию электронных плат, включая выборочную или полную перепайку;</li></ul><p>выполняют прошивку, обновляют и русифицируют ПО, настраивают приложения для корректной работы.</p><p>Сервисный центр «Инженерик» дает гарантию на все виды ремонта мобильных телефонов. </p><p>В распоряжении специалистов полный арсенал необходимого оборудования, </p><p>включая осциллографы, ультразвуковые ванны и паяльные станции. </p><p>При высоком качестве сервиса обслуживание обойдется недорого, особенно для постоянных клиентов, </p><p>которые могут получить скидки.</p><p><br/></p><p>Чтобы узнать цены на услуги по ремонту, позвоните в мастерскую по номеру +7 (***) ***-**-**.</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ui_Remont_Telefonov_Dialog = QtWidgets.QDialog()
    ui = Ui_Ui_Remont_Telefonov_Dialog()
    ui.setupUi(Ui_Remont_Telefonov_Dialog)
    Ui_Remont_Telefonov_Dialog.show()
    sys.exit(app.exec_())
