# -*- coding: utf-8 -*-
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_New_Ordies_CRM(object):
    def setupUi(self, main_New_Ordies_CRM):
        main_New_Ordies_CRM.setObjectName("main_New_Ordies_CRM")
        main_New_Ordies_CRM.resize(1270, 952)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Pictures/Screenshot from 2025-09-15 14-30-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        main_New_Ordies_CRM.setWindowIcon(icon)
        main_New_Ordies_CRM.setStyleSheet("background-color: rgb(23, 23, 23);")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(main_New_Ordies_CRM)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.scrollArea = QtWidgets.QScrollArea(main_New_Ordies_CRM)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1236, 1091))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LB_Order = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.LB_Order.setFont(font)
        self.LB_Order.setStyleSheet("color: rgb(255, 255, 255);")
        self.LB_Order.setObjectName("LB_Order")
        self.horizontalLayout.addWidget(self.LB_Order)
        self.QR_Paid = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.QR_Paid.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"")
        self.QR_Paid.setChecked(False)
        self.QR_Paid.setAutoRepeat(True)
        self.QR_Paid.setObjectName("QR_Paid")
        self.horizontalLayout.addWidget(self.QR_Paid)
        self.QR_Guarantee = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.QR_Guarantee.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"")
        self.QR_Guarantee.setChecked(False)
        self.QR_Guarantee.setAutoRepeat(False)
        self.QR_Guarantee.setAutoExclusive(False)
        self.QR_Guarantee.setObjectName("QR_Guarantee")
        self.horizontalLayout.addWidget(self.QR_Guarantee)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_7.addItem(spacerItem1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.LB_Clients = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LB_Clients.setFont(font)
        self.LB_Clients.setStyleSheet("color: rgb(255, 255, 255);")
        self.LB_Clients.setObjectName("LB_Clients")
        self.horizontalLayout_2.addWidget(self.LB_Clients)
        self.RB_PhPe = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.RB_PhPe.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"")
        self.RB_PhPe.setChecked(False)
        self.RB_PhPe.setAutoRepeat(True)
        self.RB_PhPe.setObjectName("RB_PhPe")
        self.horizontalLayout_2.addWidget(self.RB_PhPe)
        self.RB_Company = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.RB_Company.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"")
        self.RB_Company.setChecked(False)
        self.RB_Company.setAutoRepeat(False)
        self.RB_Company.setAutoExclusive(False)
        self.RB_Company.setObjectName("RB_Company")
        self.horizontalLayout_2.addWidget(self.RB_Company)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem2)
        self.QL_Client = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.QL_Client.setStyleSheet("color: rgb(255, 255, 255);")
        self.QL_Client.setText("")
        self.QL_Client.setObjectName("QL_Client")
        self.verticalLayout.addWidget(self.QL_Client)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem3)
        self.QL_Birth = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.QL_Birth.setStyleSheet("color: rgb(255, 255, 255);")
        self.QL_Birth.setText("")
        self.QL_Birth.setObjectName("QL_Birth")
        self.verticalLayout.addWidget(self.QL_Birth)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem4)
        self.QL_PhNb = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.QL_PhNb.setStyleSheet("color: rgb(255, 255, 255);")
        self.QL_PhNb.setText("")
        self.QL_PhNb.setObjectName("QL_PhNb")
        self.verticalLayout.addWidget(self.QL_PhNb)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem5)
        self.QL_Email = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.QL_Email.setStyleSheet("color: rgb(255, 255, 255);")
        self.QL_Email.setText("")
        self.QL_Email.setObjectName("QL_Email")
        self.verticalLayout.addWidget(self.QL_Email)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem6)
        self.QL_HYDFO = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.QL_HYDFO.setStyleSheet("color: rgb(255, 255, 255);")
        self.QL_HYDFO.setText("")
        self.QL_HYDFO.setObjectName("QL_HYDFO")
        self.verticalLayout.addWidget(self.QL_HYDFO)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.LB_Information = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LB_Information.setFont(font)
        self.LB_Information.setStyleSheet("color: rgb(255, 255, 255);")
        self.LB_Information.setObjectName("LB_Information")
        self.verticalLayout_2.addWidget(self.LB_Information)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem8)
        self.QL_Devis = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.QL_Devis.setStyleSheet("color: rgb(255, 255, 255);")
        self.QL_Devis.setText("")
        self.QL_Devis.setObjectName("QL_Devis")
        self.verticalLayout_2.addWidget(self.QL_Devis)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem9)
        self.QL_IME_SN = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.QL_IME_SN.setStyleSheet("color: rgb(255, 255, 255);")
        self.QL_IME_SN.setText("")
        self.QL_IME_SN.setObjectName("QL_IME_SN")
        self.verticalLayout_2.addWidget(self.QL_IME_SN)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem10)
        self.QL_Brand = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.QL_Brand.setStyleSheet("color: rgb(255, 255, 255);")
        self.QL_Brand.setText("")
        self.QL_Brand.setObjectName("QL_Brand")
        self.verticalLayout_2.addWidget(self.QL_Brand)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem11)
        self.QL_Model = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.QL_Model.setStyleSheet("color: rgb(255, 255, 255);")
        self.QL_Model.setText("")
        self.QL_Model.setObjectName("QL_Model")
        self.verticalLayout_2.addWidget(self.QL_Model)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem12)
        self.QL_TRFTR = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.QL_TRFTR.setStyleSheet("color: rgb(255, 255, 255);")
        self.QL_TRFTR.setText("")
        self.QL_TRFTR.setObjectName("QL_TRFTR")
        self.verticalLayout_2.addWidget(self.QL_TRFTR)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_7.addItem(spacerItem13)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem14)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.LB_Additional = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.LB_Additional.setMaximumSize(QtCore.QSize(600, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LB_Additional.setFont(font)
        self.LB_Additional.setStyleSheet("color: rgb(255, 255, 255);")
        self.LB_Additional.setObjectName("LB_Additional")
        self.verticalLayout_3.addWidget(self.LB_Additional)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem15)
        self.QL_Prepayment = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.QL_Prepayment.setMaximumSize(QtCore.QSize(600, 16777215))
        self.QL_Prepayment.setStyleSheet("color: rgb(255, 255, 255);")
        self.QL_Prepayment.setText("")
        self.QL_Prepayment.setObjectName("QL_Prepayment")
        self.verticalLayout_3.addWidget(self.QL_Prepayment)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem16)
        self.QL_Executor = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.QL_Executor.setMaximumSize(QtCore.QSize(600, 16777215))
        self.QL_Executor.setStyleSheet("color: rgb(255, 255, 255);")
        self.QL_Executor.setText("")
        self.QL_Executor.setObjectName("QL_Executor")
        self.verticalLayout_3.addWidget(self.QL_Executor)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem17)
        self.QL_Manager = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.QL_Manager.setMaximumSize(QtCore.QSize(600, 16777215))
        self.QL_Manager.setStyleSheet("color: rgb(255, 255, 255);")
        self.QL_Manager.setText("")
        self.QL_Manager.setObjectName("QL_Manager")
        self.verticalLayout_3.addWidget(self.QL_Manager)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem18)
        self.QL_Term = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.QL_Term.setMaximumSize(QtCore.QSize(600, 16777215))
        self.QL_Term.setStyleSheet("color: rgb(255, 255, 255);")
        self.QL_Term.setText("")
        self.QL_Term.setObjectName("QL_Term")
        self.verticalLayout_3.addWidget(self.QL_Term)
        self.verticalLayout_7.addLayout(self.verticalLayout_3)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem19)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_7.addItem(spacerItem20)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.LB_GoSe = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LB_GoSe.setFont(font)
        self.LB_GoSe.setStyleSheet("color: rgb(255, 255, 255);")
        self.LB_GoSe.setObjectName("LB_GoSe")
        self.verticalLayout_4.addWidget(self.LB_GoSe)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem21)
        self.TV_GoSe = QtWidgets.QTableView(self.scrollAreaWidgetContents)
        self.TV_GoSe.setObjectName("TV_GoSe")
        self.verticalLayout_4.addWidget(self.TV_GoSe)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem22)
        self.PB_AdGoSe = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.PB_AdGoSe.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(103, 155, 118);")
        self.PB_AdGoSe.setObjectName("PB_AdGoSe")
        self.verticalLayout_4.addWidget(self.PB_AdGoSe)
        self.verticalLayout_7.addLayout(self.verticalLayout_4)
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem23)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_7.addItem(spacerItem24)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.LB_Print = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LB_Print.setFont(font)
        self.LB_Print.setStyleSheet("color: rgb(255, 255, 255);")
        self.LB_Print.setObjectName("LB_Print")
        self.verticalLayout_5.addWidget(self.LB_Print)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem25)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.CB_TAOCW = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.CB_TAOCW.setStyleSheet("color: rgb(255, 255, 255);")
        self.CB_TAOCW.setObjectName("CB_TAOCW")
        self.horizontalLayout_4.addWidget(self.CB_TAOCW)
        self.CB_AcRe = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.CB_AcRe.setStyleSheet("color: rgb(255, 255, 255);")
        self.CB_AcRe.setObjectName("CB_AcRe")
        self.horizontalLayout_4.addWidget(self.CB_AcRe)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem26)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout_7.addLayout(self.verticalLayout_5)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_7.addItem(spacerItem27)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.PB_SO = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.PB_SO.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.PB_SO.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(28, 113, 216);")
        self.PB_SO.setObjectName("PB_SO")
        self.verticalLayout_6.addWidget(self.PB_SO)
        self.PB_SOaOP = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.PB_SOaOP.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.PB_SOaOP.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.PB_SOaOP.setObjectName("PB_SOaOP")
        self.verticalLayout_6.addWidget(self.PB_SOaOP)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_8.addWidget(self.scrollArea)

        self.retranslateUi(main_New_Ordies_CRM)
        QtCore.QMetaObject.connectSlotsByName(main_New_Ordies_CRM)

    def retranslateUi(self, main_New_Ordies_CRM):
        _translate = QtCore.QCoreApplication.translate
        main_New_Ordies_CRM.setWindowTitle(_translate("main_New_Ordies_CRM", "IT-EcoSystem"))
        self.LB_Order.setText(_translate("main_New_Ordies_CRM", "Заказ"))
        self.QR_Paid.setText(_translate("main_New_Ordies_CRM", "Платный"))
        self.QR_Guarantee.setText(_translate("main_New_Ordies_CRM", "Гарантийный"))
        self.LB_Clients.setText(_translate("main_New_Ordies_CRM", "Клиент"))
        self.RB_PhPe.setText(_translate("main_New_Ordies_CRM", "Физ. лицо"))
        self.RB_Company.setText(_translate("main_New_Ordies_CRM", "Компания"))
        self.QL_Client.setPlaceholderText(_translate("main_New_Ordies_CRM", "Клиент: ФИО"))
        self.QL_Birth.setPlaceholderText(_translate("main_New_Ordies_CRM", "Дата рождения: дд-мм-гггг"))
        self.QL_PhNb.setPlaceholderText(_translate("main_New_Ordies_CRM", "Тедефон"))
        self.QL_Email.setPlaceholderText(_translate("main_New_Ordies_CRM", "Эл почта"))
        self.QL_HYDFO.setPlaceholderText(_translate("main_New_Ordies_CRM", "Откуда узнали?"))
        self.LB_Information.setText(_translate("main_New_Ordies_CRM", "Информация"))
        self.QL_Devis.setPlaceholderText(_translate("main_New_Ordies_CRM", "Вид устройства"))
        self.QL_IME_SN.setPlaceholderText(_translate("main_New_Ordies_CRM", "IMEI / SN"))
        self.QL_Brand.setPlaceholderText(_translate("main_New_Ordies_CRM", "Бренд"))
        self.QL_Model.setPlaceholderText(_translate("main_New_Ordies_CRM", "Модель"))
        self.QL_TRFTR.setPlaceholderText(_translate("main_New_Ordies_CRM", "Причина обращения"))
        self.LB_Additional.setText(_translate("main_New_Ordies_CRM", "Дополнительное "))
        self.QL_Prepayment.setPlaceholderText(_translate("main_New_Ordies_CRM", "Предоплата, ₽"))
        self.QL_Executor.setPlaceholderText(_translate("main_New_Ordies_CRM", "Исполнитель"))
        self.QL_Manager.setPlaceholderText(_translate("main_New_Ordies_CRM", "Менеджер"))
        self.QL_Term.setPlaceholderText(_translate("main_New_Ordies_CRM", "Срок: дд-мм-гггг, чч:мм"))
        self.LB_GoSe.setText(_translate("main_New_Ordies_CRM", "Товары и Услуги"))
        self.PB_AdGoSe.setText(_translate("main_New_Ordies_CRM", "Добавить"))
        self.LB_Print.setText(_translate("main_New_Ordies_CRM", "Печать"))
        self.CB_TAOCW.setText(_translate("main_New_Ordies_CRM", "Акт выполненных работ"))
        self.CB_AcRe.setText(_translate("main_New_Ordies_CRM", "Приемная квитанция"))
        self.PB_SO.setText(_translate("main_New_Ordies_CRM", "Сохранить"))
        self.PB_SOaOP.setText(_translate("main_New_Ordies_CRM", "Сохранить и открыть"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_New_Ordies_CRM = QtWidgets.QDialog()
    ui = Ui_main_New_Ordies_CRM()
    ui.setupUi(main_New_Ordies_CRM)
    main_New_Ordies_CRM.show()
    sys.exit(app.exec_())
