# -*- coding: utf-8 -*-
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_Servies_CRM(object):
    def setupUi(self, main_Servies_CRM):
        main_Servies_CRM.setObjectName("main_Servies_CRM")
        main_Servies_CRM.resize(651, 380)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Pictures/Screenshot from 2025-09-15 14-30-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        main_Servies_CRM.setWindowIcon(icon)
        main_Servies_CRM.setStyleSheet("background-color: rgb(23, 23, 23);")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(main_Servies_CRM)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lineEdit = QtWidgets.QLineEdit(main_Servies_CRM)
        self.lineEdit.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_4.addWidget(self.lineEdit)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(main_Servies_CRM)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.pushButton = QtWidgets.QPushButton(main_Servies_CRM)
        self.pushButton.setStyleSheet("color: rgb(28, 113, 216);")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.tableWidget = QtWidgets.QTableWidget(main_Servies_CRM)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.scrollArea = QtWidgets.QScrollArea(main_Servies_CRM)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 629, 68))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(main_Servies_CRM)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.pushButton_2 = QtWidgets.QPushButton(main_Servies_CRM)
        self.pushButton_2.setStyleSheet("color: rgb(28, 113, 216);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.tableWidget_2 = QtWidgets.QTableWidget(main_Servies_CRM)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tableWidget_2)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)

        self.retranslateUi(main_Servies_CRM)
        QtCore.QMetaObject.connectSlotsByName(main_Servies_CRM)

    def retranslateUi(self, main_Servies_CRM):
        _translate = QtCore.QCoreApplication.translate
        main_Servies_CRM.setWindowTitle(_translate("main_Servies_CRM", "IT-EcoSystem"))
        self.lineEdit.setPlaceholderText(_translate("main_Servies_CRM", "Поиск"))
        self.label.setText(_translate("main_Servies_CRM", "Товар"))
        self.pushButton.setText(_translate("main_Servies_CRM", "Добавить +"))
        self.label_2.setText(_translate("main_Servies_CRM", "Услуга"))
        self.pushButton_2.setText(_translate("main_Servies_CRM", "Добавить +"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_Servies_CRM = QtWidgets.QDialog()
    ui = Ui_main_Servies_CRM()
    ui.setupUi(main_Servies_CRM)
    main_Servies_CRM.show()
    sys.exit(app.exec_())
