# -*- coding: utf-8 -*-
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_Position_CRM(object):
    def setupUi(self, main_Position_CRM):
        main_Position_CRM.setObjectName("main_Position_CRM")
        main_Position_CRM.resize(582, 409)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Pictures/Screenshot from 2025-09-15 14-30-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        main_Position_CRM.setWindowIcon(icon)
        main_Position_CRM.setStyleSheet("background-color: rgb(23, 23, 23);")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(main_Position_CRM)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scrollArea = QtWidgets.QScrollArea(main_Position_CRM)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 562, 389))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.QL_NaGS = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.QL_NaGS.setStyleSheet("color: rgb(255, 255, 255);")
        self.QL_NaGS.setText("")
        self.QL_NaGS.setObjectName("QL_NaGS")
        self.verticalLayout_3.addWidget(self.QL_NaGS)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.QL_Price = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.QL_Price.setStyleSheet("color: rgb(255, 255, 255);")
        self.QL_Price.setText("")
        self.QL_Price.setObjectName("QL_Price")
        self.verticalLayout.addWidget(self.QL_Price)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem2)
        self.QL_Discount = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.QL_Discount.setStyleSheet("color: rgb(255, 255, 255);")
        self.QL_Discount.setText("")
        self.QL_Discount.setObjectName("QL_Discount")
        self.verticalLayout.addWidget(self.QL_Discount)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem4)
        self.QL_Property = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.QL_Property.setStyleSheet("color: rgb(255, 255, 255);")
        self.QL_Property.setText("")
        self.QL_Property.setObjectName("QL_Property")
        self.verticalLayout_2.addWidget(self.QL_Property)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem5)
        self.QL_Guarantee = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.QL_Guarantee.setStyleSheet("color: rgb(255, 255, 255);")
        self.QL_Guarantee.setText("")
        self.QL_Guarantee.setObjectName("QL_Guarantee")
        self.verticalLayout_2.addWidget(self.QL_Guarantee)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem6)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem7)
        self.QL_Quantity = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.QL_Quantity.setStyleSheet("color: rgb(255, 255, 255);")
        self.QL_Quantity.setText("")
        self.QL_Quantity.setObjectName("QL_Quantity")
        self.verticalLayout_3.addWidget(self.QL_Quantity)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem8)
        self.PB_SOGS = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.PB_SOGS.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.PB_SOGS.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(28, 113, 216);")
        self.PB_SOGS.setObjectName("PB_SOGS")
        self.verticalLayout_3.addWidget(self.PB_SOGS)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_6.addWidget(self.scrollArea)

        self.retranslateUi(main_Position_CRM)
        QtCore.QMetaObject.connectSlotsByName(main_Position_CRM)

    def retranslateUi(self, main_Position_CRM):
        _translate = QtCore.QCoreApplication.translate
        main_Position_CRM.setWindowTitle(_translate("main_Position_CRM", "IT-EcoSystem"))
        self.QL_NaGS.setPlaceholderText(_translate("main_Position_CRM", "Название"))
        self.QL_Price.setPlaceholderText(_translate("main_Position_CRM", "Цена, ₽"))
        self.QL_Discount.setPlaceholderText(_translate("main_Position_CRM", "Скидка, %"))
        self.QL_Property.setPlaceholderText(_translate("main_Position_CRM", "Себестоимость, ₽"))
        self.QL_Guarantee.setPlaceholderText(_translate("main_Position_CRM", "Гарантия, дн"))
        self.QL_Quantity.setPlaceholderText(_translate("main_Position_CRM", "Количество"))
        self.PB_SOGS.setText(_translate("main_Position_CRM", "Сохранить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_Position_CRM = QtWidgets.QDialog()
    ui = Ui_main_Position_CRM()
    ui.setupUi(main_Position_CRM)
    main_Position_CRM.show()
    sys.exit(app.exec_())
